apiVersion: v1
kind: Secret
metadata:
  name: hospital-backend-secret
type: Opaque
data:
  DB_USERNAME: VGVsY28=
  DB_PASSWORD: VGVsY28xMjMuIw==


## echo -n "username" | base64
## echo -n "password" | base64
