apiVersion: v1
kind: Secret
metadata:
  name: hospital-backend-secret
type: Opaque
data:
  DB_USERNAME: aG9zcGl0YWxhZG1pbg==
  DB_PASSWORD: SG9zcGl0YWxhcHAzNCM=


## echo -n "username" | base64
## echo -n "password" | base64
